### ISSUE TITLE
Rate limit, doesn`t download 

### ISSUE THREAD

**Issue by sagar3506** [hakanersu/codecourse-downloader#13]
![image](https://user-images.githubusercontent.com/9415704/34667327-977d6eb0-f48e-11e7-8f33-0c7f122085b1.png)
 its give me  this error

**Comment by hakanersu** [comment]
Hi @sagar3506 

is it happening with all your downloads or after downloaded some videos?

if you getting this error after downloded some videos, my best guess is; codocourse implemented an api rate limit and limiting requests. Can you check codecourse website after this errors for checking any rate limit message.

**Comment by sagar3506** [comment]
![image](https://user-images.githubusercontent.com/9415704/34667822-adfb685c-f490-11e7-9ee2-97f5e5b4022b.png)
now its downloading without doing anything i dont know how but its working

**Comment by hakanersu** [comment]
it seems rate limit than. I guess you will get that error again.

**Comment by sagar3506** [comment]
lets see

**Comment by sagar3506** [comment]
yes i getting error again after some lesson downloaded what to do now ?

**Comment by hakanersu** [comment]
Not much, ill ask codecourse.com for easy way to get lessons information for downloading videos otherwise with api limit i cant do much.
 
Script visits every course for getting information than visits every page so its a lot of requests.

**Comment by sagar3506** [comment]
i hope you get solution very soon

**Comment by sagar3506** [comment]
sir can you please give me your mail address @hakanersu

**Comment by DCzajkowski** [comment]
It's Vimeo's rate limits. https://twitter.com/alexjgarrett/status/951201752229007361
The new site will have an ability to download all :)
