### ISSUE TITLE
[InvalidArgumentException]  The current node list is empty

### ISSUE THREAD

**Issue by sagar3506** [hakanersu/codecourse-downloader#14]
@hakanersu today i got new error [InvalidArgumentException]  The current node list is empty

please help me solve out this

![image](https://preview.ibb.co/ejxbk8/Untitled.png)

**Comment by hakanersu** [comment]
I guess it is related with new design. With new design most of the functionality of this package broken now. Until its fixed try to use new sites download section.

With new design with download section it is a bit easy to fix and it can be faster than before.

**Comment by ipkpjersi** [comment]
I really hope this isn't too hard to fix. This is one of my favourite programs! Thank you for making it.

**Comment by ipkpjersi** [comment]
@hakanersu  Any update on this? I would absolutely love for this to be updated.

**Comment by reed1** [comment]
I made a fork here meanwhile

[https://github.com/reed1/codecourse-downloader](https://github.com/reed1/codecourse-downloader)

**Comment by ipkpjersi** [comment]
Thanks for the fork but it's not quite working yet:

!()[https://i.imgur.com/3E3Osqi.png]

!()[https://i.imgur.com/b9HliB6.png]

**Comment by ipkpjersi** [comment]
Thanks @reed1 for the fork but it's not quite working yet, this used to work for me before:

![](https://i.imgur.com/3E3Osqi.png)

![](https://i.imgur.com/b9HliB6.png)

**Comment by reed1** [comment]
@ipkpjersi oops sorry, please pull again and modify your .env based on .env.example

**Comment by ipkpjersi** [comment]
Tried it but it didn't work, it acts like there's no more series/courses to download when there is:

![](https://i.imgur.com/ustFyAs.png)

**Comment by reed1** [comment]
![image](https://user-images.githubusercontent.com/1814324/41775690-2c9ce0ce-764f-11e8-94b4-301d7c26954c.png)

Sorry I can't reproduce that, it should be like above image, also this is just temporary before original author made changes to conform the new site design, if you need my help please open an issue in the fork instead :sunglasses:

**Comment by hakanersu** [comment]
@ipkpjersi Not yet, i don't have active subscription i hope ill upgrade soon.
@reed1 You can create a pull request or i can give push access to this repo :)

**Comment by reed1** [comment]
@hakanersu I think I messed up with many things there, I also disabled the "download all series" capability because I think that will create a lot of burden to Alex's quota on S3. Also I don't know if it works for everyone, I'm using PHP 7 at the moment. Feel free to copy whichever needed :)

**Comment by hakanersu** [comment]
@reed1 Thanks, your work helped me a lot specially nuxt part.

**Comment by reed1** [comment]
glad to hear.. : )

**Comment by ipkpjersi** [comment]
@hakanersu Do you have plans to continue providing the download all series functionality? I am about 10 series behind currently while I have the majority of them it would be nice to automatically download the rest of them and automatically any of the new ones that come out this year.

**Comment by hakanersu** [comment]
@ipkpjersi Yes, main reason why i create this repository is download all function. Im currently working on develop branch for new version.

**Comment by sagar3506** [comment]
@hakanersu bro i can provide one active subscription  just give me  your mail

**Comment by hakanersu** [comment]
@sagar3506 thanks it would be great, it seems codecourse reactivation part not working for me. Reported to alex via twitter.

hakanersu@gmail.com thanks again.

**Comment by sagar3506** [comment]
send check it @hakanersu

**Comment by hakanersu** [comment]
So far i guess completed most of the script  thanks to @reed1 and @sagar3506 Check develop branch for first working version. Still have some bugs.

https://media.giphy.com/media/fR7TgplQHAYHUHgihG/giphy.mp4
