### ISSUE TITLE
URI must be a string or UriInterface

### ISSUE THREAD

**Issue by ipkpjersi** [hakanersu/codecourse-downloader#15]
Hi,

I am getting an error when I try to download all courses: ![](https://i.imgur.com/zcqzPTW.png)

I made sure I am using the latest version from master branch.

Thanks.

**Comment by hakanersu** [comment]
Did you update your .env with updated .env.example file?

**Comment by ipkpjersi** [comment]
Yep that was it, thank you. I will now close this as it is solved.
