### ISSUE TITLE
Download fails at middle

### ISSUE THREAD

**Issue by shirshak55** [hakanersu/codecourse-downloader#17]
may be internet issue but download always fails . And the huge problem is it downloads incomplete file so no use of running script again and again unless I delete file.

Can we use aria2c wrapper?

https://github.com/shiny/php-aria2#install

Thank You

**Comment by hakanersu** [comment]
I don't have any experience about aria2/php-aria2 but it seems nice, i will take a look

**Comment by shirshak55** [comment]
@hakanersu  I used it and it was really promising. If you like I can make PR for you (or us as this is opensource)

**Comment by shirshak55** [comment]
See this screenshot. I use it not just for error but also for multiple download at same time with multiple connections :)

<img width="1680" alt="screen shot 2018-08-02 at 6 31 34 pm" src="https://user-images.githubusercontent.com/8097377/43584584-7ebb31dc-9682-11e8-8a2c-cef13ccc347b.png">


Internet here is slow otherwise I would never download from codecourse.

**Comment by hakanersu** [comment]
I'd appreciate any pr but I guess it must be an optional method/parameter for the downloader. I don't want to break current functionality. But I'll definitely use aria2 it seems very nice.

**Comment by shirshak55** [comment]
yes I will take care of that
