### ISSUE TITLE
PHP Notice:  Undefined property: stdClass

### ISSUE THREAD

**Issue by lunadiotic** [hakanersu/codecourse-downloader#21]
When I trying to download, terminal show this log:
I'm using php 7.1.23 btw

Logged in successfully, collecting courses.
PHP Notice:  Undefined property: stdClass::$total in /home/kiddie/Program/ccourse/src/App.php on line 47
PHP Notice:  Undefined property: stdClass::$last_page in /home/kiddie/Program/ccourse/src/App.php on line 47
Total  lessons found, fetching   pages for courses.
PHP Notice:  Undefined property: stdClass::$last_page in /home/kiddie/Program/ccourse/src/App.php on line 52
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Symfony\Component\Console\Helper\ProgressBar::__construct() must be of the type integer, null given, called in /home/kiddie/Program/ccourse/src/App.php on line 52 and defined in /home/kiddie/Program/ccourse/vendor/symfony/console/Helper/ProgressBar.php:54
Stack trace:
#0 /home/kiddie/Program/ccourse/src/App.php(52): Symfony\Component\Console\Helper\ProgressBar->__construct(Object(Symfony\Component\Console\Output\ConsoleOutput), NULL)
#1 /home/kiddie/Program/ccourse/src/Commands/DownloadCommand.php(58): App\App->download(Object(Symfony\Component\Console\Output\ConsoleOutput), Array)
#2 /home/kiddie/Program/ccourse/vendor/symfony/console/Command/Command.php(251): App\Commands\DownloadCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /home/kiddie/Program/ccourse/vendor/symfony/console/Application.php(886): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvI in /home/kiddie/Program/ccourse/vendor/symfony/console/Helper/ProgressBar.php on line 54

**Comment by lunadiotic** [comment]
I think it's because codecourse has new structure with their website.
I'm trying to download all or single series still not work.

**Comment by hakanersu** [comment]
Sorry about late answer i'll try to look at it.

**Comment by lunadiotic** [comment]
I hope you still want to update this project. great work btw.

**Comment by hakanersu** [comment]
I guess its working now.

**Comment by lunadiotic** [comment]
Awesome, I just feeling that this project was updated. Thanks man!
