### ISSUE TITLE
Can't fetch redirect url

### ISSUE THREAD

**Issue by lunadiotic** [hakanersu/codecourse-downloader#23]
![screenshot_91](https://user-images.githubusercontent.com/18319373/49418039-029f4880-f7b3-11e8-92f5-34d5236d41f4.png)
I dont know why always stop in here.
My account still pro member.

**Comment by lunadiotic** [comment]
![screenshot_92](https://user-images.githubusercontent.com/18319373/49418166-70e40b00-f7b3-11e8-9243-f68f8f207ea7.png)

**Comment by lunadiotic** [comment]
![screenshot_96](https://user-images.githubusercontent.com/18319373/49483224-fecbfe80-f864-11e8-9906-83dd549c3185.png)
when I check today

**Comment by hakanersu** [comment]
Fixed after last update, but website constantly changing.

**Comment by lunadiotic** [comment]
> Fixed after last update, but website constantly changing.

You are so awesome dude. Many thanks with this project because I dont have internet connection at home. So I wanna download it all when using public connection
