### ISSUE TITLE
Can't download videos

### ISSUE THREAD

**Issue by ipkpjersi** [hakanersu/codecourse-downloader#24]
Hi,

I seem to get an error when downloading videos: ![](https://i.imgur.com/JlR1rQj.png)

It simply creates blank folders: ![](https://i.imgur.com/dmSaHB1.png)

As far as I can tell, my .env file is correct and I already did `composer install` so I do not know why this is not working.

Thanks.

**Comment by hakanersu** [comment]
Fixed after last update, but website constantly changing.

**Comment by ipkpjersi** [comment]
I'm not sure if this is fixed. I did download videos - however, it downloaded all my videos over again because it now has series number in front of the video name:
![](https://i.imgur.com/XzKpD5u.png)

Also, it seems to have an error still when I run it:

![](https://i.imgur.com/KGRBoVr.png)

Is there any way to have an option for the old naming back of courses so it can find my existing videos? Also, I have 116GB of videos downloaded before but of the videos it tried downloading yesterday it only downloaded 83GB of videos so I guess that means it is erroring out like in the screenshot above.

Thanks.

**Comment by hakanersu** [comment]
Sorry there is no option for naming old way. Sorry for invonvience and downloading issues must be fixed after last merge request.
