### ISSUE TITLE
invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by sagarsolanki3** [hakanersu/codecourse-downloader#25]
@hakanersu 

![Image of Yaktocat](https://cdn.pbrd.co/images/HSbihvm.png)

its say 

Undefined offset: 3 in E:\sp\src\Parser.php on line 45
All videos dowloaded for course: 313-Reusable Laravel comments
   0/0  [>---------------------------]   0%
PHP Notice:  Undefined offset: 3 in E:\sp\src\Parser.php on line 45

Notice: Undefined offset: 3 in E:\sp\src\Parser.php on line 45
All videos dowloaded for course: 312-Cleanly iterating over JavaScript objects

**Comment by lunadiotic** [comment]
![screenshot_2018-12-19_11-27-29](https://user-images.githubusercontent.com/18319373/50199054-4c765a00-0381-11e9-8a3e-12face727b33.png)
Same things here

**Comment by hakanersu** [comment]
i hope after @doanhvv merge request it is fixed.
