### ISSUE TITLE
Looking for a similar downloader for mapt videos

### ISSUE THREAD

**Issue by rajkum2** [hakanersu/codecourse-downloader#3]
Hello Sir hakanersu,
I am planning to develop a similar downloader to mapt [https://www.packtpub.com/mapt/login](url)
videos.
I have created a repo [https://github.com/kumaralg2/mapt-video-downloader.git](url) for that.
As I am new to this development, I need your help to develop me that downloader.
My email:kumar.alg2@gmail.com
I did not know how to contact you so, I am using this to communicate with you.
Please kindly look at this .
Thanks,

**Comment by hakanersu** [comment]
Hello @kumaralg2 

i cant reach your repository. First of all try to complete below steps

1. Examine login page, any csrf token needed?
2. Login from browser and find success message for successful login.
3. Try to login on browser with wrong credentials/unactive subscription and gather error messages.
4. Check this method and try to create a simple login script: [Login Method](https://github.com/hakanersu/codecourse-downloader/blob/master/src/Process/Remote.php#L27)

**Comment by rajkum2** [comment]
Hi Hakan,
Really Great to get a reply from you, and thank you very much for replying
me.

I have added you as the collaborator to this repo(
https://github.com/kumaralg2/mapt-video-downloader.git) I have created,
please check it.
https://github.com/kumaralg2/mapt-video-downloader

Actually, I am new to this type of programming, I am basically a front end
guy who worked on IOS Development mostly.
So I am trying to understand and getting to know the code.

As, you have mentioned that was the first thing I was doing..trying to
login to the website through my credentials:
email:kumar.alg2@gmail.com
password:

One of the Video's Link:
https://www.packtpub.com/mapt/video/big-data-and-business-intelligence/9781787128033/15331/15599/The+Course+Overview

I tried to do the login as you have done for the codecourse but was no
success.
I will try again with the steps you gave, will see how it goes.
But please check it on your side too..

Thanks,
Kiran.

**Comment by rajkum2** [comment]
There is no need of csrf token.

**Comment by rajkum2** [comment]
Link for the website login:
https://www.packtpub.com/mapt/login

- I am not able to find success message.
- For wrong credentials error message:
Sorry, you entered an invalid email address and password combination.

**Comment by kumaralg2** [comment]
Link for the website login:
https://www.packtpub.com/mapt/login

- I am not able to find success message.
- For wrong credentials error message:
Sorry, you entered an invalid email address and password combination.

**Comment by rajkum2** [comment]
I am able to login to the website, but the video url's in the site are not just as simple slugs in codecourse.I am getting error when I am trying to access the files..!!

**Comment by hakanersu** [comment]
Video source files in **div#video-content_media** you should able to download with that link.
`https://d1ft11egbn8l.cloudfront.net/Python Machine Learning Projects/Package/videos/video1_1.mp4?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6XC9cL2QxZnQxMWVnYm44bC5jbG91ZGZyb250Lm5ldFwvUHl0aG9uJTIwTWFjaGluZSUyMExlYXJuaW5nJTIwUHJvamVjdHNcL1BhY2thZ2VcL3ZpZGVvc1wvdmlkZW8xXzEubXA0IiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNDkxOTUyNTE1fX19XX0_&Signature=ARnTpNX2p0flhvqmH~tad8ii7QR2l3eDX1qw3i7vb4iJbn5lo94qwGKrlif80ofEXFyrPy-gqGjPzdTAPOIneZL~7jVhRfgVH6VtKda~iSNxnsnvnpFPEtqccU2Ms9BdS1tywMSkS6Mg8qD~GBFhvEEwvci-18~PpJZufthOILI_&Key-Pair-Id=APKAJTJLPJQL5PVZ47FA`

**Comment by rajkum2** [comment]
Great thanks.a lot.!! You no need to do this, but you are really great to lend your time in this..!!But It was really interesting how we can automate this through web scrapping.I will look into it, and I hope I can find some solution for this..Thanks.

**Comment by rajkum2** [comment]
Hi hakanersu, 
is there any way to download the e-book also?
[https://www.packtpub.com/mapt/book/game-development/9781783988556](url)
It would be great if you can help me out..
