### ISSUE TITLE
Downloaded folders are empty

### ISSUE THREAD

**Issue by iamopk** [hakanersu/codecourse-downloader#34]
![2019-11-16-20-09-31](https://user-images.githubusercontent.com/31550132/68996614-90cdeb00-08ad-11ea-8b66-e74e31d2dfdf.png)
No lessons were downloaded

**Comment by hiddenlucas** [comment]
Same issue for me...
I just start using this one https://github.com/codecourse/cli and works for me well.

**Comment by hakanersu** [comment]
Good to see offical tool.

**Comment by hakanersu** [comment]
Black friday is here so i reactivate my account and fixed downloader.
