### ISSUE TITLE
Does it support resume? Or it starts from the beginning each time?

### ISSUE THREAD

**Issue by cyantarek** [hakanersu/codecourse-downloader#35]

**Comment by hakanersu** [comment]
Unfortunately it starts from beginning.

**Comment by cyantarek** [comment]
No, it doesn't. At first, it checks what files are downloaded already. Then it skips those files and proceed next until it finds files that are not downloaded.

**Comment by hakanersu** [comment]
:smile:  i thought you were asking continue to individual videos which is not downloaded properly and yes it checks and continues video series.
