### ISSUE TITLE
Impossible to create the root directory "/Users/yourname/prefer-clone-path/Downloads". Linux, how to call the path?

### ISSUE THREAD

**Issue by ghost** [hakanersu/codecourse-downloader#4]
It gives me an error if I try to download all videos.

[League\Flysystem\Exception]                                                 
  Impossible to create the root directory "/Users/yourname/prefer-clone-path/  
  Downloads".

I am on a Linux PC, how do I should call the directory?

**Comment by hakanersu** [comment]
First of all you have to edit .env (change .env.example to .env) file and change DOWNLOAD_FOLDER path to your desired folder. For example go to Documents directory and create codecourse folder than  in terminal and type pwd in that folder it gives your full path. It must be like **/home/youruser/Documents/codecourse**

**Comment by ghost** [comment]
It's giving me now this error block:

vagrant@homestead:~/sites/codecourse-downloader$ php codecourse download

Collecting remote series ...
 20/20 [============================] 100%
Calculating downloading information.

                                                                            
  [League\Flysystem\Exception]                                              
  Impossible to create the root directory "/home/filip/Videos/codecourse".  
                                                                            

download [<series>]

What now? I'm sorry but I paid for Codecourse premium membership but want to download all series to watch offline because I am in two weeks in holidays and have no internet there...

**Comment by hakanersu** [comment]
Can you create /home/filip/Videos/codecourse than try to run downloader.

**Comment by ghost** [comment]
Ohhh my gosh. I was in my vagrant homestead machine. I tried it now out of the machine, it's working beautifully ....... Thank you **very, very** much. Have a nice evening!
