### ISSUE TITLE
Cant Download

### ISSUE THREAD

**Issue by JacquesvanWyk** [hakanersu/codecourse-downloader#5]
![image](https://user-images.githubusercontent.com/12008702/27821681-6e815320-60a3-11e7-8553-3de3d83b16b4.png)

I got it working till this point.I changed the .env and login is working,i also had problem with folder creating so i changed that to c:/codecourse/downloads.After this it ran but came up with above problem in picture.It says cant download.What could this problem be?

Thanks

**Comment by hakanersu** [comment]
Hi, that error coming from download video method which getting download url from website and create folder for downloaded video. So there 2 possible reasons; codecourse changed video provider (which i cant test right now, dont have active subscription) or DOWNLOAD_FOLDER env variable is wrong. It is possible to problem is download folder or windows issue.
