### ISSUE TITLE
download files wont open

### ISSUE THREAD

**Issue by mehranhadidi** [hakanersu/codecourse-downloader#6]
hello, 

i installed the library and tried to download some series but downloaded files wont open.

![image](https://user-images.githubusercontent.com/897774/27823886-e8f39d4a-60bf-11e7-875e-e1d11bbe6292.png)
![image](https://user-images.githubusercontent.com/897774/27823897-f064dd5a-60bf-11e7-8fd2-808e4753fe75.png)

and also all the files are 4.6 KB:

![image](https://user-images.githubusercontent.com/897774/27823975-2e3b38a4-60c0-11e7-8873-d972fc287151.png)

i also check the permissions. what should i do?

**Comment by hakanersu** [comment]
Delete all of them and try again. Maybe codecourse video provider can be changed. I don't have active subscription so if your problem persist let me know, I will check in a few days.
